"""add etl mvp workspace

Revision ID: 0008_add_etl_mvp_workspace
Revises: 0007_align_model_columns
Create Date: 2026-08-27 09:04:35.181566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0008_add_etl_mvp_workspace'
down_revision: Union[str, None] = '0007_align_model_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostgreSQL schemas are not emitted by Alembic autogenerate.
    op.execute("CREATE SCHEMA IF NOT EXISTS etl")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_recipes',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by_actor_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='etl'
    )
    op.create_index(op.f('ix_etl_data_recipes_id'), 'data_recipes', ['id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_data_recipes_operation'), 'data_recipes', ['operation'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_data_recipes_status'), 'data_recipes', ['status'], unique=False, schema='etl')
    op.create_index('uq_etl_data_recipes_name_lower', 'data_recipes', [sa.literal_column('lower(name)')], unique=True, schema='etl')
    op.create_table('data_sources',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_credential_version', sa.Integer(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='etl'
    )
    op.create_index(op.f('ix_etl_data_sources_id'), 'data_sources', ['id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_data_sources_kind'), 'data_sources', ['kind'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_data_sources_status'), 'data_sources', ['status'], unique=False, schema='etl')
    op.create_index('uq_etl_data_sources_name_lower', 'data_sources', [sa.literal_column('lower(name)')], unique=True, schema='etl')
    op.create_table('data_source_credentials',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('credential_type', sa.String(length=20), nullable=False),
    sa.Column('encrypted_secret', sa.Text(), nullable=True),
    sa.Column('header_name', sa.String(length=100), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['etl.data_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'version', name='uq_etl_source_credential_version'),
    schema='etl'
    )
    op.create_index(op.f('ix_etl_data_source_credentials_id'), 'data_source_credentials', ['id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_data_source_credentials_source_id'), 'data_source_credentials', ['source_id'], unique=False, schema='etl')
    op.create_table('runs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('recipe_id', sa.Uuid(), nullable=True),
    sa.Column('definition_version', sa.Integer(), nullable=False),
    sa.Column('definition_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('credential_version', sa.Integer(), nullable=True),
    sa.Column('artifact_id', sa.String(length=100), nullable=True),
    sa.Column('celery_task_id', sa.String(length=100), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('output_size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("(kind = 'INGESTION' AND source_id IS NOT NULL AND recipe_id IS NULL) OR (kind = 'TRANSFORMATION' AND source_id IS NULL AND recipe_id IS NOT NULL)", name='ck_etl_runs_owner_matches_kind'),
    sa.CheckConstraint("(status = 'SUCCEEDED' AND completed_at IS NOT NULL) OR (status = 'FAILED' AND completed_at IS NOT NULL) OR status IN ('PENDING', 'RUNNING')", name='ck_etl_runs_completion_matches_status'),
    sa.ForeignKeyConstraint(['recipe_id'], ['etl.data_recipes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['etl.data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='etl'
    )
    op.create_index(op.f('ix_etl_runs_celery_task_id'), 'runs', ['celery_task_id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_runs_id'), 'runs', ['id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_runs_kind'), 'runs', ['kind'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_runs_recipe_id'), 'runs', ['recipe_id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_runs_source_id'), 'runs', ['source_id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_runs_status'), 'runs', ['status'], unique=False, schema='etl')
    op.create_table('datasets',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('record_count', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('produced_by_run_id', sa.Uuid(), nullable=True),
    sa.Column('created_by_actor_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(kind = 'RAW' AND source_id IS NOT NULL) OR (kind = 'DERIVED' AND source_id IS NULL AND produced_by_run_id IS NOT NULL)", name='ck_etl_datasets_origin_matches_kind'),
    sa.ForeignKeyConstraint(['produced_by_run_id'], ['etl.runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['etl.data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('produced_by_run_id', name='uq_etl_dataset_producing_run'),
    schema='etl'
    )
    op.create_index(op.f('ix_etl_datasets_id'), 'datasets', ['id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_datasets_kind'), 'datasets', ['kind'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_datasets_name'), 'datasets', ['name'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_datasets_produced_by_run_id'), 'datasets', ['produced_by_run_id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_datasets_source_id'), 'datasets', ['source_id'], unique=False, schema='etl')
    op.create_table('dataset_records',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['etl.datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'position', name='uq_etl_dataset_record_position'),
    schema='etl'
    )
    op.create_index(op.f('ix_etl_dataset_records_dataset_id'), 'dataset_records', ['dataset_id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_dataset_records_id'), 'dataset_records', ['id'], unique=False, schema='etl')
    op.create_table('recipe_inputs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('recipe_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.Column('selector_kind', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('dataset_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("(selector_kind = 'SOURCE' AND source_id IS NOT NULL AND dataset_id IS NULL) OR (selector_kind = 'DATASET' AND source_id IS NULL AND dataset_id IS NOT NULL)", name='ck_etl_recipe_input_selector'),
    sa.ForeignKeyConstraint(['dataset_id'], ['etl.datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipe_id'], ['etl.data_recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['etl.data_sources.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'alias', name='uq_etl_recipe_input_alias'),
    sa.UniqueConstraint('recipe_id', 'position', name='uq_etl_recipe_input_position'),
    schema='etl'
    )
    op.create_index(op.f('ix_etl_recipe_inputs_id'), 'recipe_inputs', ['id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_recipe_inputs_recipe_id'), 'recipe_inputs', ['recipe_id'], unique=False, schema='etl')
    op.create_table('run_inputs',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('dataset_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['etl.datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['etl.runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'position', name='uq_etl_run_input_position'),
    schema='etl'
    )
    op.create_index(op.f('ix_etl_run_inputs_dataset_id'), 'run_inputs', ['dataset_id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_run_inputs_id'), 'run_inputs', ['id'], unique=False, schema='etl')
    op.create_index(op.f('ix_etl_run_inputs_run_id'), 'run_inputs', ['run_id'], unique=False, schema='etl')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_etl_run_inputs_run_id'), table_name='run_inputs', schema='etl')
    op.drop_index(op.f('ix_etl_run_inputs_id'), table_name='run_inputs', schema='etl')
    op.drop_index(op.f('ix_etl_run_inputs_dataset_id'), table_name='run_inputs', schema='etl')
    op.drop_table('run_inputs', schema='etl')
    op.drop_index(op.f('ix_etl_recipe_inputs_recipe_id'), table_name='recipe_inputs', schema='etl')
    op.drop_index(op.f('ix_etl_recipe_inputs_id'), table_name='recipe_inputs', schema='etl')
    op.drop_table('recipe_inputs', schema='etl')
    op.drop_index(op.f('ix_etl_dataset_records_id'), table_name='dataset_records', schema='etl')
    op.drop_index(op.f('ix_etl_dataset_records_dataset_id'), table_name='dataset_records', schema='etl')
    op.drop_table('dataset_records', schema='etl')
    op.drop_index(op.f('ix_etl_datasets_source_id'), table_name='datasets', schema='etl')
    op.drop_index(op.f('ix_etl_datasets_produced_by_run_id'), table_name='datasets', schema='etl')
    op.drop_index(op.f('ix_etl_datasets_name'), table_name='datasets', schema='etl')
    op.drop_index(op.f('ix_etl_datasets_kind'), table_name='datasets', schema='etl')
    op.drop_index(op.f('ix_etl_datasets_id'), table_name='datasets', schema='etl')
    op.drop_table('datasets', schema='etl')
    op.drop_index(op.f('ix_etl_runs_status'), table_name='runs', schema='etl')
    op.drop_index(op.f('ix_etl_runs_source_id'), table_name='runs', schema='etl')
    op.drop_index(op.f('ix_etl_runs_recipe_id'), table_name='runs', schema='etl')
    op.drop_index(op.f('ix_etl_runs_kind'), table_name='runs', schema='etl')
    op.drop_index(op.f('ix_etl_runs_id'), table_name='runs', schema='etl')
    op.drop_index(op.f('ix_etl_runs_celery_task_id'), table_name='runs', schema='etl')
    op.drop_table('runs', schema='etl')
    op.drop_index(op.f('ix_etl_data_source_credentials_source_id'), table_name='data_source_credentials', schema='etl')
    op.drop_index(op.f('ix_etl_data_source_credentials_id'), table_name='data_source_credentials', schema='etl')
    op.drop_table('data_source_credentials', schema='etl')
    op.drop_index('uq_etl_data_sources_name_lower', table_name='data_sources', schema='etl')
    op.drop_index(op.f('ix_etl_data_sources_status'), table_name='data_sources', schema='etl')
    op.drop_index(op.f('ix_etl_data_sources_kind'), table_name='data_sources', schema='etl')
    op.drop_index(op.f('ix_etl_data_sources_id'), table_name='data_sources', schema='etl')
    op.drop_table('data_sources', schema='etl')
    op.drop_index('uq_etl_data_recipes_name_lower', table_name='data_recipes', schema='etl')
    op.drop_index(op.f('ix_etl_data_recipes_status'), table_name='data_recipes', schema='etl')
    op.drop_index(op.f('ix_etl_data_recipes_operation'), table_name='data_recipes', schema='etl')
    op.drop_index(op.f('ix_etl_data_recipes_id'), table_name='data_recipes', schema='etl')
    op.drop_table('data_recipes', schema='etl')
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS etl")
