from enum import Enum

class EventType(str, Enum):
    FILE_UPLOADED = "FILE_UPLOADED"
    FILE_PROCESSED = "FILE_PROCESSED"
    JOB_STARTED = "JOB_STARTED"
    JOB_COMPLETED = "JOB_COMPLETED"
    JOB_FAILED = "JOB_FAILED"
    QUALITY_CHECK_PASSED = "QUALITY_CHECK_PASSED"
    QUALITY_CHECK_FAILED = "QUALITY_CHECK_FAILED"
